### ISSUE TITLE
Add  Experience, Health and Hunger

### ISSUE THREAD

**Issue by Elad-PenDragon** [nsg/SyncNBT#11]
Player experience and levels do not transfer over, is this an issue?

**Comment by nsg** [comment]
Technically, that not a "item", but I'm considering to add exp, health and hunger anyway to give it a little more "connected" experience between the servers.

**Comment by nsg** [comment]
Added in 0.3, but not that well tested.

**Comment by Kainzo** [comment]
Can these be toggles please? Having EXP/Health/Hunger save/sync messes with popular RPG plugins like Heroes.

**Comment by nsg** [comment]
Yes, currently most things are quite static. I will add a option for that later. This ticket talks about adding exp/hp/hunger and what is tested and works, I will close this ticket.
